export enum RouteNames {
  DISCLAIMER = 'disclaimer',
  TRANSFER = 'transfer',
  TRANSFER_STEPS = 'transfer-steps',
  QUICK_PAY = 'quick-pay',
  SELECT_TOKEN = 'select-token',
  SELECT_HUB = 'select-hub',
  HOME = 'home',
  NO_CONNECTED_TOKEN = 'no-connected-token',
  CHANNELS = 'channels',
  OPEN_CHANNEL = 'open-channel',
  ACCOUNT_ROOT = 'account-root',
  ACCOUNT_BACKUP = 'account-backup',
  ACCOUNT_RAIDEN = 'account-raiden',
  ACCOUNT_SETTINGS = 'account-settings',
  ACCOUNT_WITHDRAWAL = 'account-withdrawal',
  ACCOUNT_UDC = 'account-udc',
  NOTIFICATIONS = 'notifications',
}
