# File paths
keystore-path = '/opt/raiden/config/keys'
datadir = '/opt/raiden/data'
password-file = '/opt/raiden/config/passwd'

# Networking
eth-rpc-endpoint = "http://localhost:8545"
network-id = 4321

environment-type = "development"
accept-disclaimer = true
api-address = "0.0.0.0:5002"
matrix-server = "http://localhost"

routing-mode = "pfs"
pathfinding-service-address = "http://localhost:6000"
# Misc
address = "0xCBC49ec22c93DB69c78348C90cd03A323267db86"

log-json = true

# Log settings
[log-config]
"raiden" = "DEBUG"
