platform :android do
  before_all do
    Dotenv.overload ".env.secrets"
  end

  desc "Deploy a new beta track version to the Google Play Store"
  lane :deploy do
    yarn(command: 'capacitor:build --android', package_path: './package.json')
    gradle(task: 'clean', project_dir: './android/')
    gradle(
      task: 'bundle',
      project_dir: './android/',
      properties: {
        "android.injected.signing.store.file" => "#{Dir.pwd}/../keyfiles/google_play_store_upload_keystore.jks",
        "android.injected.signing.store.password" => "#{ENV["GOOGLE_PLAY_STORE_UPLOAD_KEYSTORE_PASSWORD"]}",
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => "#{ENV["GOOGLE_PLAY_STORE_UPLOAD_KEYSTORE_PASSWORD"]}",
      },

    )
    upload_to_play_store(
      track: "beta",
      aab: "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}",
      skip_upload_apk: true,
    )
  end
end

# vim: filetype=ruby
