name: Checks

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  changelog-check:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/changelog-reminder
