name: Checks

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  changelog-check:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: 'ChangeLog Reminder'
        uses: ./.github/actions/changelog-reminder
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ROOTS: '["raiden-ts", "raiden-dapp"]'
          CHANGELOG_FILE: 'CHANGELOG.md'

  block-fixup:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - name: 'Block Fixup Commit Merge'
          uses: 13rac1/block-fixup-merge-action@v2.0.0
